/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.swingapp.view.window;

import cl.duoc.swingapp.view.entity.LoginView;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * @author cmartinezs
 */
public class LoginForm extends javax.swing.JFrame {
  private boolean listenerLogin;
  private boolean listenerCancel;

  private static final java.util.logging.Logger logger =
      java.util.logging.Logger.getLogger(LoginForm.class.getName());

  /** Creates new form LoginForm */
  public LoginForm() {
    this.initComponents();
    this.setLocationRelativeTo(null);
    this.setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    loginAppTitle = new javax.swing.JLabel();
    loginTitle = new javax.swing.JLabel();
    lblUsername = new javax.swing.JLabel();
    fdUsername = new javax.swing.JTextField();
    lblPassword = new javax.swing.JLabel();
    fdPassword = new javax.swing.JPasswordField();
    btnLogin = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    setSize(new java.awt.Dimension(350, 500));

    loginAppTitle.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
    loginAppTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginAppTitle.setText("Swing APP");

    loginTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
    loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginTitle.setText("Ingreso de Usuario");

    lblUsername.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
    lblUsername.setText("Nombre de Usuario");

    fdUsername.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

    lblPassword.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
    lblPassword.setText("Contraseña");

    fdPassword.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
    fdPassword.setPreferredSize(new java.awt.Dimension(64, 24));

    btnLogin.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
    btnLogin.setText("Ingresar");

    btnCancel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
    btnCancel.setText("Cancelar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                loginAppTitle,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addComponent(
                loginTitle,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                fdPassword,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        btnLogin,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        164,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(
                                        btnCancel,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        178,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                lblUsername,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                295,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                lblPassword,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                252,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fdUsername))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addComponent(
                        loginAppTitle,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        60,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        loginTitle,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        60,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblUsername)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        fdUsername,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblPassword)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        fdPassword,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                btnLogin,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                40,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                btnCancel,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                40,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
  }

  public LoginView getView() {
    String username = this.fdUsername.getText().trim();
    String password = new String(this.fdPassword.getPassword()).trim();
    return new LoginView(username, password);
  }

  public void setLoginListener(ActionListener listener) {
    if (this.listenerLogin) {
      this.showErrorMessage("Ya existe una acción para el botón de ingresar");
      return;
    }
    this.btnLogin.addActionListener(listener);
    this.listenerLogin = true;
  }

  public void setCancelListener(ActionListener listener) {
    if (this.listenerCancel) {
      this.showErrorMessage("Ya existe una acción para el botón de cancelar");
      return;
    }
    this.btnCancel.addActionListener(listener);
    this.listenerCancel = true;
  }

  public void showErrorMessage(String errorMessage) {
    System.out.println("Mostrando mensaje de error: " + errorMessage);
    JOptionPane.showMessageDialog(this, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
  }

  public void showSuccessMessage(String successMessage) {
    System.out.println("Mostrando mensaje de éxito: " + successMessage);
    JOptionPane.showMessageDialog(this, successMessage, "Éxito", JOptionPane.INFORMATION_MESSAGE);
  }

  public int showConfirmationMessage(String confirmationMessage) {
    System.out.println("Mostrando mensaje de confirmación: " + confirmationMessage);
    return JOptionPane.showConfirmDialog(this, confirmationMessage, "Confirmación", JOptionPane.YES_NO_OPTION);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnLogin;
  private javax.swing.JPasswordField fdPassword;
  private javax.swing.JTextField fdUsername;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblUsername;
  private javax.swing.JLabel loginAppTitle;
  private javax.swing.JLabel loginTitle;
  // End of variables declaration//GEN-END:variables
}
