/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cl.duoc.swingapp.view.window;

import cl.duoc.swingapp.view.entity.LoginView;

import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 * @author cmartinezs
 */
public class LoginDialog extends javax.swing.JDialog {
  private boolean listenerLogin;
  private boolean listenerCancel;

  private static final java.util.logging.Logger logger =
      java.util.logging.Logger.getLogger(LoginDialog.class.getName());

  /** Creates new form LoginForm */
  public LoginDialog() {
    super((JFrame) null, true);
    this.initComponents();
    this.setLocationRelativeTo(null);
    this.setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    loginAppTitle = new javax.swing.JLabel();
    loginTitle = new javax.swing.JLabel();
    lblUsername = new javax.swing.JLabel();
    lblPassword = new javax.swing.JLabel();
    fdUsername = new javax.swing.JTextField();
    fdPassword = new javax.swing.JPasswordField();
    separator = new javax.swing.JSeparator();
    btnLogin = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Swing APP: Ingreso de Usuario");

    loginAppTitle.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 36)); // NOI18N
    loginAppTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginAppTitle.setText("Swing APP");

    loginTitle.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 24)); // NOI18N
    loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginTitle.setText("Ingreso de Usuario");

    lblUsername.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 18)); // NOI18N
    lblUsername.setText("Nombre de Usuario");

    lblPassword.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 18)); // NOI18N
    lblPassword.setText("Contraseña");

    fdUsername.setFont(new java.awt.Font("Liberation Sans", Font.PLAIN, 18)); // NOI18N

    fdPassword.setFont(new java.awt.Font("Liberation Sans", Font.PLAIN, 18)); // NOI18N
    fdPassword.setPreferredSize(new java.awt.Dimension(64, 24));

    btnLogin.setFont(new java.awt.Font("Liberation Sans", Font.PLAIN, 18)); // NOI18N
    btnLogin.setText("Ingresar");

    btnCancel.setFont(new java.awt.Font("Liberation Sans", Font.PLAIN, 18)); // NOI18N
    btnCancel.setText("Cancelar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separator)
                            .addComponent(
                                loginTitle,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                318,
                                Short.MAX_VALUE)
                            .addComponent(fdUsername)
                            .addComponent(
                                fdPassword,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUsername)
                                            .addComponent(lblPassword))
                                    .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(
                                btnLogin,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                btnCancel,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addContainerGap())
            .addGroup(
                layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(
                        layout
                            .createSequentialGroup()
                            .addContainerGap()
                            .addComponent(
                                loginAppTitle,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                318,
                                Short.MAX_VALUE)
                            .addContainerGap())));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(
                        loginTitle,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        60,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblUsername)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        fdUsername,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblPassword)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        fdPassword,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        separator,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        10,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        btnLogin,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        btnCancel,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(
                layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(
                        layout
                            .createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(
                                loginAppTitle,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                60,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(424, Short.MAX_VALUE))));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            LoginDialog dialog = new LoginDialog();
            dialog.addWindowListener(
                new java.awt.event.WindowAdapter() {
                  @Override
                  public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                  }
                });
            dialog.setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnLogin;
  private javax.swing.JPasswordField fdPassword;
  private javax.swing.JTextField fdUsername;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblUsername;
  private javax.swing.JLabel loginAppTitle;
  private javax.swing.JLabel loginTitle;
  private javax.swing.JSeparator separator;

  // End of variables declaration//GEN-END:variables

  public LoginView getView() {
    String username = this.fdUsername.getText().trim();
    String password = new String(this.fdPassword.getPassword()).trim();
    return new LoginView(username, password);
  }

  public void setLoginListener(ActionListener listener) {
    if (this.listenerLogin) {
      this.showErrorMessage("Ya existe una acción para el botón de ingresar");
      return;
    }
    this.btnLogin.addActionListener(listener);
    this.listenerLogin = true;
  }

  public void setCancelListener(ActionListener listener) {
    if (this.listenerCancel) {
      this.showErrorMessage("Ya existe una acción para el botón de cancelar");
      return;
    }
    this.btnCancel.addActionListener(listener);
    this.listenerCancel = true;
  }

  public void showErrorMessage(String errorNoCredentials) {
    JOptionPane.showMessageDialog(this, errorNoCredentials, "Error", JOptionPane.ERROR_MESSAGE);
  }

  public void showSuccessMessage(String successLogin) {
    JOptionPane.showMessageDialog(this, successLogin, "Éxito", JOptionPane.INFORMATION_MESSAGE);
  }

  public int showConfirmationMessage(String message) {
    return JOptionPane.showConfirmDialog(this, message, "Confirmación", JOptionPane.YES_NO_OPTION);
  }
}
