package cl.duoc.swingapp.view.window;

import cl.duoc.swingapp.view.entity.UserView;
import cl.duoc.swingapp.view.exception.ViewException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.function.Consumer;

/**
 * @author cmartinezs
 */
public class UserForm extends javax.swing.JDialog {
  private final Long userId;
  private Consumer<Long> loadUserCallback;

  private static final java.util.logging.Logger logger =
      java.util.logging.Logger.getLogger(UserForm.class.getName());

  /** Creates new form UserForm */
  public UserForm(Frame parent, Long userId, boolean modal) {
    super(parent, modal);
    this.userId = userId;
    initComponents();
    setLocationRelativeTo(parent);
    loadListeners();
  }

  private void loadListeners() {
    btnCancel.addActionListener(
        e -> {
          int confirm =
              JOptionPane.showConfirmDialog(
                  this, "¿Está seguro que desea cancelar?", "Confirmar", JOptionPane.YES_NO_OPTION);
          if (confirm == JOptionPane.YES_OPTION) {
            setVisible(false);
          }
        });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblUsername = new javax.swing.JLabel();
    lblPassword = new javax.swing.JLabel();
    lblEmail = new javax.swing.JLabel();
    txtUsername = new javax.swing.JTextField();
    txtPassword = new javax.swing.JPasswordField();
    txtEmail = new javax.swing.JTextField();
    formTitle = new javax.swing.JLabel();
    panelButtons = new javax.swing.JPanel();
    btnSave = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    lblUsername.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 15)); // NOI18N
    lblUsername.setText("Nombre de Usuario");

    lblPassword.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 15)); // NOI18N
    lblPassword.setText("Contraseña");

    lblEmail.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 15)); // NOI18N
    lblEmail.setText("Correo Electrónico");

    formTitle.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 36)); // NOI18N
    formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    formTitle.setText("Registro de Usuario");

    btnSave.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 15)); // NOI18N
    btnSave.setText("Guardar");

    btnCancel.setFont(new java.awt.Font("Liberation Sans", Font.BOLD, 15)); // NOI18N
    btnCancel.setText("Cancelar");

    javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
    panelButtons.setLayout(panelButtonsLayout);
    panelButtonsLayout.setHorizontalGroup(
        panelButtonsLayout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                panelButtonsLayout
                    .createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(btnSave)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCancel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    panelButtonsLayout.setVerticalGroup(
        panelButtonsLayout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                panelButtonsLayout
                    .createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(
                        panelButtonsLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnSave)
                            .addComponent(btnCancel))
                    .addContainerGap(17, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                panelButtons,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                lblUsername,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                lblPassword,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                lblEmail,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsername)
                                            .addComponent(txtPassword)
                                            .addComponent(txtEmail))))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addComponent(
                        formTitle,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        60,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(
                                txtUsername,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(
                                txtPassword,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(
                                txtEmail,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        panelButtons,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            UserForm dialog = new UserForm(new javax.swing.JFrame(), null, true);
            dialog.addWindowListener(
                new java.awt.event.WindowAdapter() {
                  @Override
                  public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                  }
                });
            dialog.setVisible(true);
          }
        });
  }

  public void setLoadUserCallback(Consumer<Long> loadUserCallback) {
    this.loadUserCallback = loadUserCallback;
  }

  public void loadUser() throws ViewException {
    if (userId == null) {
      return;
    }
    if (loadUserCallback == null) {
      throw new ViewException("No existe función para cargar el usuario");
    }
    loadUserCallback.accept(userId);
  }

  public void addSaveListener(ActionListener l) {
    btnSave.addActionListener(l);
  }

  public UserView getUserView() {
    String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    String email = txtEmail.getText().trim();
    return new UserView(userId, username, password, email);
  }

  public boolean validateUserView() {
    String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    String email = txtEmail.getText().trim();
    if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
      JOptionPane.showMessageDialog(
          this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
      return false;
    }
    return true;
  }

  public void setUserView(UserView userView) {
    if (userView == null) {
      txtUsername.setText("");
      txtPassword.setText("");
      txtEmail.setText("");
      return;
    }
    txtUsername.setText(userView.getUsername());
    txtPassword.setText(userView.getPassword());
    txtEmail.setText(userView.getEmail());
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnSave;
  private javax.swing.JLabel formTitle;
  private javax.swing.JLabel lblEmail;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblUsername;
  private javax.swing.JPanel panelButtons;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtUsername;
  // End of variables declaration//GEN-END:variables
}
